### ISSUE TITLE
[Cloud][Dataproc] java.lang.ClassNotFoundException: scala.Product$class on Dataproc 2.0 when running Hibench

### ISSUE THREAD

**Issue by HongW2019** [oap-project/oap-mllib#134]
We are going to reproduce the OAP MLlib performance gain on Dataproc 2.0, OAP MLlib works well on Dataproc, but when running baseline, Hibench met the issue as below:

![image](https://user-images.githubusercontent.com/30172512/133776175-b5e58fa2-e9e0-4282-9458-2b36afe6cb7b.png)

When we run performance bigdata workflow on August 17, we didn't met such issue, but Dataproc 2.0 has updated Spark-3.1.2  jars/ on August 26 as picture shows.

![image](https://user-images.githubusercontent.com/30172512/133776859-faa3f1e9-6d3b-4e23-a222-02d5ef8abd8e.png)

**Comment by HongW2019** [comment]
@xwu99 @zhixingheyi-tian  Please help track this issue, thanks.

**Comment by xwu99** [comment]
I think it's probably due to the support of Spark 3.1.2 and Scala 2.12.14. Currently we only support up to Spark 3.1.1 and Scala 2.12.10.

**Comment by HongW2019** [comment]
Fixed on HiBench side. HiBench [#685](https://github.com/Intel-bigdata/HiBench/pull/685)
