### ISSUE TITLE
[Doc] Improve README for oap-project/oap-mllib

### ISSUE THREAD

**Issue by xwu99** [oap-project/oap-mllib#23]

**Comment by xwu99** [comment]
@HongW2019 I have revised README a bit. Could you review and revise some links for OAP 1.1 release?

**Comment by HongW2019** [comment]
> @HongW2019 I have revised README a bit. Could you review and revise some links for OAP 1.1 release?

Sure, will submit another PR to add some modifications today.

**Comment by xwu99** [comment]
@HongW2019 could you reproduce #52 to revise master as well?
