### ISSUE TITLE
[BUG] Wrong test data path

### ISSUE THREAD

**Issue by xwu99** [oap-project/oap-mllib#230]
val centroidData = TestCommon.readCSV("src/test/scala/data/kmeans_dense_train_centroids.csv")

        val sourceData = TestCommon.readCSV("src/test/scala/data/covcormoments_dense.csv")

should be in src/test/resources/data

**Comment by xwu99** [comment]
@minmingzhu

**Comment by xwu99** [comment]
#262

**Comment by minmingzhu** [comment]
It has been fixed and can be closed
