### ISSUE TITLE
[Example] Refactor CPU & GPU examples

### ISSUE THREAD

**Issue by xwu99** [oap-project/oap-mllib#282]
* Separate scala and python examples into examples/scala and examples/python directories. Change names to kmeans-pyspark and kmeans-scala. etc.
* Move GPU resource files to conf
* Rename run.sh & run-gpu-standalone.sh to run-cpu.sh & run-gpu.sh
* Add incomplete pyspark examples

**Comment by xwu99** [comment]
@argentea could you help to refactor examples?

**Comment by argentea** [comment]
Sure. Will do.
