### ISSUE TITLE
[Release] Meet hang issue when running PCA algorithm.

### ISSUE THREAD

**Issue by haojinIntel** [oap-project/oap-mllib#46]
In our automatic tests for OAP product, we found that using Intel-MLlib to run PCA and Kmeans algorithms often meet hanging issue which lead to block the whole workflow. The phenomenon is shown in the picture below：
![image](https://user-images.githubusercontent.com/44394375/113071438-4d042900-91f7-11eb-8eda-ee93bc86f027.png)

**Comment by haojinIntel** [comment]
@zhixingheyi-tian @xwu99 Is that issue similar to the one of OAP-1.0?

**Comment by xwu99** [comment]
It should be. We still use the same oneCCL version as the latest code is not released yet. It should be fixed in the next release of oneCCL.

**Comment by xwu99** [comment]
should be fixed with #50
