### ISSUE TITLE
No performance benefit when using Intel-MLlib to run ALS algorithm.

### ISSUE THREAD

**Issue by haojinIntel** [oap-project/oap-mllib#48]
I run ALS algorithm with Intel-MLlib and no performance benefit obtained. The configuration of ALS.conf is showed below:
![image](https://user-images.githubusercontent.com/44394375/113235973-91b2c180-92d6-11eb-8013-25d010342d17.png)
And the configuration of spark is showed below:
![image](https://user-images.githubusercontent.com/44394375/113236353-464ce300-92d7-11eb-9f86-eaafbcad869f.png)

**Comment by haojinIntel** [comment]
Component | Configuration | Status | Succeeded   Cases | Failed   cases | Baseline   time/s | Optimized   time/s | Performance   gain/% | Details
-- | -- | -- | -- | -- | -- | -- | -- | --
oap-mllib | ALS_5GB_INTEL_MLLIB | SUCCEED | 1 | 0 | 634.37 | 643.837 | -1.5 | Details

**Comment by haojinIntel** [comment]
@xwu99 @zhixingheyi-tian Please help to tracking the issue. Thanks!

**Comment by xwu99** [comment]
@haojinIntel What version are you testing? ALS is not included in 1.1.0 branch

**Comment by xwu99** [comment]
@haojinIntel ALS was added to OAP 1.1 from #50
