### ISSUE TITLE
Migrate CI from Travis to GitHub Actions

### ISSUE THREAD

**Issue by xwu99** [oap-project/oap-mllib#6]
Due to the license change of Travis, we would like to migrate CI to GitHub Actions and remove Travis

**Comment by xwu99** [comment]
@HongW2019 @zhixingheyi-tian I found there are some scripts in .github/workflows, Do you think they are useful for mllib?

**Comment by HongW2019** [comment]
There were some rules about PR title format for developers, if we need this check, like PR's title should start with [ML-Issuesid], I will submit another PR to modify it. @xwu99 @zhixingheyi-tian

**Comment by xwu99** [comment]
I see. but report_ram_log.yml and tpch.yml are related ?

**Comment by HongW2019** [comment]
> I see. but report_ram_log.yml and tpch.yml are related ?

They are not related for title rules. I notice native-sql-engine and arrow-data-source have updated them,  I guess it is not related to mllib.

**Comment by xwu99** [comment]
@zhztheplayer report_ram_log.yml and tpch.yml are not related to mllib right? Could I delete them safely?

**Comment by zhztheplayer** [comment]
@xwu99 I think it should be safe to delete them here.
