### ISSUE TITLE
Using Intel-MLlib to run ALS algorithm sometimes meets hanging issue.

### ISSUE THREAD

**Issue by haojinIntel** [oap-project/oap-mllib#70]
The same issue like https://github.com/oap-project/oap-mllib/issues/46. The frequency of this issue is not that high.

**Comment by xwu99** [comment]
@haojinIntel Thanks. Could you be more specific on what stage you hang, any output from stdout/stderr? Since I have not met oneCCL hang for a while.

**Comment by haojinIntel** [comment]
Here are some snapshots of this issue:
![image](https://user-images.githubusercontent.com/44394375/122849814-cca91c00-d33e-11eb-8053-1838cbab73cd.png)
![image](https://user-images.githubusercontent.com/44394375/122849996-16920200-d33f-11eb-82eb-9aa3e8e520ff.png)
