### ISSUE TITLE
Some shared libs are missing in 1.1.1 release

### ISSUE THREAD

**Issue by zjf2012** [oap-project/oap-mllib#95]
21/07/13 02:44:23 WARN TaskSetManager: Lost task 5.0 in stage 3.0 (TID 456) (10.17.11.102 executor 4): java.lang.UnsatisfiedLinkError: /tmp/MLlibDAL_e234b184-8429-439d-b4cf-f82e98384246/lib/libMLlibDAL.so: libtbbmalloc.so.2: cannot open shared object file: No such file or directory
        at org.apache.spark.ml.util.LibLoader.loadLibMLlibDAL(LibLoader.java:74)
21/07/13 02:44:23 WARN TaskSetManager: Lost task 0.0 in stage 3.0 (TID 451) (10.17.11.103 executor 2): java.lang.UnsatisfiedLinkError: /tmp/MLlibDAL_20553d11-b459-4aa7-9ea6-dfd36d214183/lib/libMLlibDAL.so: libtbb.so.12: cannot open shared object file: No such file or directory
        at org.apache.spark.ml.util.LibLoader.loadLibMLlibDAL(LibLoader.java:74)
21/07/13 02:44:23 WARN TaskSetManager: Lost task 0.1 in stage 3.0 (TID 458) (10.17.11.102 executor 4): java.lang.UnsatisfiedLinkError: org.apache.spark.ml.util.OneDAL$.cCheckPlatformCompatibility()Z
        at org.apache.spark.ml.util.OneDAL$.cCheckPlatformCompatibility(Native Method)
21/07/13 02:44:24 INFO TaskSetManager: Lost task 0.2 in stage 3.0 (TID 459) on 10.17.11.102, executor 3: java.lang.UnsatisfiedLinkError (org.apache.spark.ml.util.OneDAL$.cCheckPlatformCompatibility()Z) [duplicate 1]
21/07/13 02:44:24 WARN TaskSetManager: Lost task 3.0 in stage 3.0 (TID 454) (10.17.11.102 executor 3): java.lang.UnsatisfiedLinkError: /tmp/MLlibDAL_8b608000-e0a8-4871-9877-a7a38e2a22ff/lib/libMLlibDAL.so: libtbb.so.12: cannot open shared object file: No such file or directory

**Comment by xwu99** [comment]
@haojinIntel Did you ever run Standalone mode, did you encounter the similar issue?
