### ISSUE TITLE
[SDLe][Klocwork] Security vulnerabilities found by static code scan

### ISSUE THREAD

**Issue by HongW2019** [oap-project/oap-mllib#98]
- [ ] Null pointer dereference of 'columnsLine' where null is returned from a method
- [ ]  Input stream 'new FileReader(...)' is not closed on exit.
- [ ] Input stream 'new FileReader(...)' is not closed on exit.
- [ ] Null pointer dereference of 'valuesLine' where null is returned from a method
- [ ] Null pointer dereference of 'rowIndexLine' where null is returned from a method

![image](https://user-images.githubusercontent.com/30172512/126763426-970a150b-620b-4e7a-b763-f0b3b4bb42f2.png)
![image](https://user-images.githubusercontent.com/30172512/126763570-9cfc724f-f35a-43e5-83d5-f87bc916d9af.png)
![image](https://user-images.githubusercontent.com/30172512/126763612-2ef41bd5-14b0-41eb-8fca-d6349a0f7997.png)
![image](https://user-images.githubusercontent.com/30172512/126763637-49aaa4ef-0536-47fd-a560-46e398dee4ad.png)
![image](https://user-images.githubusercontent.com/30172512/126763706-9b2535a8-cd68-4889-a0cd-e7355ede0165.png)

**Comment by HongW2019** [comment]
@xwu99 Please take a review and help fix, thanks!

**Comment by xwu99** [comment]
I am cleaning code. some of the code is redundant.
